import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]

JSON_PATH = BASE_DIR / "ai-service" / "dataset" / "metadata" / "project_metadata_records_100.json"
OUTPUT_SQL = BASE_DIR / "infra" / "db" / "generated_seed_from_metadata.sql"


def sql_text(value):
    if value is None:
        return "NULL"

    value = str(value)
    value = value.replace("'", "''")
    return f"'{value}'"


def short_text(value, limit):
    if not value:
        return ""
    value = str(value).replace("\x00", "")
    if len(value) > limit:
        return value[:limit]
    return value


def map_domain(language, title, summary):
    text = f"{title} {summary} {language}".lower()

    if any(word in text for word in [
        "ai", "artificial intelligence", "machine learning", "deep learning",
        "llm", "rag", "diffusion", "transformer", "model", "recommendation",
        "computer vision", "image generation", "chatbot", "neural"
    ]):
        return "인공지능"

    if any(word in text for word in [
        "spring", "api", "server", "backend", "jpa", "database",
        "java", "go", "rest", "microservice", "crud"
    ]):
        return "백엔드"

    if any(word in text for word in [
        "react", "typescript", "javascript", "html", "css",
        "web", "frontend", "dashboard", "ui", "browser"
    ]):
        return "웹"

    if any(word in text for word in [
        "android", "kotlin", "mobile", "ios", "app"
    ]):
        return "앱"

    if any(word in text for word in [
        "data", "sql", "analytics", "analysis", "pandas", "pipeline"
    ]):
        return "데이터분석"

    if any(word in text for word in [
        "security", "auth", "xray", "vulnerability", "password", "token"
    ]):
        return "보안"

    if any(word in text for word in [
        "cloud", "docker", "kubernetes", "devops", "deploy"
    ]):
        return "클라우드"

    if any(word in text for word in [
        "embedded", "iot", "arduino", "raspberry", "firmware"
    ]):
        return "임베디드"

    return "웹"


def make_test_embedding(index, dim=384):
    values = [0.0] * dim

    first = index % dim
    second = (index * 7) % dim
    third = (index * 13) % dim

    values[first] = 1.0
    values[second] = 0.5
    values[third] = 0.25

    return "[" + ",".join(str(v) for v in values) + "]"


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        records = json.load(f)

    lines = []
    lines.append("-- Generated from ai-service/dataset/metadata/project_metadata_records_100.json")
    lines.append("-- JSON metadata seed data for local PostgreSQL test")
    lines.append("-- This file is generated by infra/db/generate_seed_from_metadata.py")
    lines.append("")

    for idx, record in enumerate(records[:100], start=1):
        source = record.get("source", {})

        project_key = record.get("project_id", f"unknown/project-{idx}")
        title = short_text(source.get("repo_name") or project_key.split("/")[-1], 255)
        summary = short_text(source.get("repo_description") or "", 1000)
        description = short_text(source.get("repo_description") or "", 3000)
        readme = short_text(source.get("readme") or "", 8000)
        language = short_text(source.get("repo_language") or "Unknown", 100)
        repo_url = source.get("repo_url") or ""
        storage_key = f"metadata/{project_key.replace('/', '_')}.json"

        domain = map_domain(language, title, summary)
        embedding = make_test_embedding(idx)

        lines.append(f"""
INSERT INTO projects (
    title,
    summary,
    description,
    readme,
    project_year,
    semester,
    difficulty,
    domain,
    is_team,
    status,
    visibility,
    author_id,
    created_at,
    updated_at
)
SELECT
    {sql_text(title)},
    {sql_text(summary)},
    {sql_text(description)},
    {sql_text(readme)},
    2026,
    '1학기',
    'MEDIUM',
    {sql_text(domain)},
    TRUE,
    'APPROVED',
    'PUBLIC',
    1,
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM projects WHERE title = {sql_text(title)}
);
""")

        lines.append(f"""
UPDATE projects
SET domain = {sql_text(domain)}
WHERE title = {sql_text(title)};
""")

        lines.append(f"""
INSERT INTO project_tech_stack (project_id, tech_stack)
SELECT p.id, {sql_text(language)}
FROM projects p
WHERE p.title = {sql_text(title)}
AND NOT EXISTS (
    SELECT 1
    FROM project_tech_stack pts
    WHERE pts.project_id = p.id
    AND pts.tech_stack = {sql_text(language)}
);
""")

        lines.append(f"""
INSERT INTO project_files (
    file_name,
    file_type,
    size,
    storage_key,
    uploaded_at,
    project_id
)
SELECT
    {sql_text(title + "-metadata.json")},
    'JSON',
    0,
    {sql_text(storage_key)},
    NOW(),
    p.id
FROM projects p
WHERE p.title = {sql_text(title)}
ON CONFLICT (storage_key) DO NOTHING;
""")

        metadata_json = json.dumps(
            {
                "project_id": project_key,
                "repo_url": repo_url,
                "repo_name": title,
                "language": language,
                "domain": domain,
            },
            ensure_ascii=False,
        )

        lines.append(f"""
INSERT INTO project_vectors (
    project_id,
    embedding,
    metadata
)
SELECT
    p.id,
    {sql_text(embedding)}::vector,
    {sql_text(metadata_json)}::jsonb
FROM projects p
WHERE p.title = {sql_text(title)}
ON CONFLICT (project_id) DO UPDATE
SET embedding = EXCLUDED.embedding,
    metadata = EXCLUDED.metadata;
""")

    OUTPUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated: {OUTPUT_SQL}")
    print(f"records: {min(len(records), 100)}")


if __name__ == "__main__":
    main()